name: kidsadventure
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.8
  path: ^1.8.3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/avatar.png
    - assets/images/logo.png
    - assets/images/animals.png
    - assets/images/PIG.png
    - assets/images/NUMERO.png
    - assets/images/COUNT.png
    - assets/images/SHEP.png
    - assets/images/splash.png
    - assets/images/avatar1.png
    - assets/images/avatar2.png
    - assets/images/avatar3.png
    - assets/images/avatar4.png
    - assets/images/avatar5.png
    - assets/images/avatar6.png
    - assets/fonts/
    
  uses-material-design: true

  # Custom Fonts
  fonts:
    - family: Jomhuria
      fonts:
        - asset: assets/fonts/Jomhuria-Regular.ttf

    - family: Rampart
      fonts:
        - asset: assets/fonts/RampartOne-Regular.ttf
    
    - family: Lemon
      fonts:
        - asset: assets/fonts/Lemon-Regular.ttf
